# Generated by Django 4.1.2 on 2022-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужской'), ('women', 'Женский')], default=1, max_length=16, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
