# Generated by Django 4.1.2 on 2022-10-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_curator',
        ),
    ]
