# Generated by Django 4.1.2 on 2022-10-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0003_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studying_process.directionoftraining', verbose_name='Направление подготовки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studying_process.group', verbose_name='Учебная группа'),
            preserve_default=False,
        ),
    ]
