# Generated by Django 4.1.2 on 2022-10-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0003_group_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studying_process.group', verbose_name='Учебная группа'),
        ),
    ]
