# Generated by Django 4.1.2 on 2022-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0004_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Учебная дисциплина',
                'verbose_name_plural': 'Учебные дисциплины',
            },
        ),
        migrations.CreateModel(
            name='DirectionOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название направления')),
            ],
        ),
    ]
