# Generated by Django 4.1.2 on 2022-10-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0006_directionoftraining_disciplines_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionoftraining',
            options={'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.RemoveField(
            model_name='directionoftraining',
            name='groups',
        ),
    ]
