# Generated by Django 4.1.2 on 2022-10-28 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studying_process', '0007_alter_directionoftraining_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionoftraining',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_process.directionoftraining', verbose_name='Направление подготовки'),
        ),
    ]
