# Generated by Django 4.1.2 on 2022-10-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0009_alter_directionoftraining_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionoftraining',
            name='disciplines',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to='studying_process.academicdiscipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_process.directionoftraining', verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_process.group', verbose_name='Учебная группа'),
        ),
    ]
