# Generated by Django 4.1.2 on 2022-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_process', '0010_alter_directionoftraining_disciplines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdiscipline',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='directionoftraining',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название группы'),
        ),
    ]
