version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
    ports:
      - '15432:5432'

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A settings worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A settings beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis

  backend:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: wait-for db:5432 -- ./entrypoint.sh
    depends_on:
      - db
    ports:
      - '8000:8000'

volumes:
  pgdata:

